services:
  nzuzo-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_FACTORY_ADDRESS: ${VITE_FACTORY_ADDRESS}
        VITE_TOKEN_ADDRESS: ${VITE_TOKEN_ADDRESS}
        VITE_INFURA_RPC_URL: ${VITE_INFURA_RPC_URL}
        VITE_FAUCET_URL: ${VITE_FAUCET_URL}
    container_name: nzuzo-app
    restart: always
    ports:
      - "8082:80"
    env_file:
      - ./.env
    networks:
      - nzuzo-network

  nzuzo-faucet:
    build:
      context: ./faucet
      dockerfile: Dockerfile
    container_name: nzuzo-faucet
    restart: always
    ports:
      - "${FAUCET_PORT:-3001}:3001"
    environment:
      - SEPOLIA_RPC_URL=${SEPOLIA_RPC_URL}
      - PRIVATE_KEY=${PRIVATE_KEY}
    env_file:
      - ./.env
    networks:
      - nzuzo-network

networks:
  nzuzo-network:
    driver: bridge
